# Generated by Django 4.1.5 on 2023-01-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('genero', models.CharField(choices=[('Acción', 'acción'), ('aventura', 'Aventura'), ('estrategia', 'Estrategia'), ('rol', 'Rol'), ('simulación', 'Simulación'), ('otro', 'Otro')], default='accion', max_length=15)),
                ('creador', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('telefonoContacto', models.IntegerField()),
                ('emailContacto', models.EmailField(max_length=254)),
                ('imagenVideojuego', models.ImageField(blank=True, null=True, upload_to='assets/')),
            ],
        ),
    ]
