# Generated by Django 4.1.5 on 2023-01-28 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_videojuego_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='genero',
            field=models.CharField(choices=[('accion', 'Acción'), ('aventura', 'Aventura'), ('estrategia', 'Estrategia'), ('rol', 'Rol'), ('simulación', 'Simulación'), ('otro', 'Otro')], default='accion', max_length=15),
        ),
    ]
