# Generated by Django 4.1.5 on 2023-01-29 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_alter_videojuego_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videojuego',
            old_name='year',
            new_name='lanzamiento',
        ),
    ]
