# Generated by Django 4.1.5 on 2023-01-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_rename_year_videojuego_lanzamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='nombre',
            field=models.CharField(max_length=45),
        ),
    ]
